config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #get 'static/about'
  #get 'static/home'
  #root "static#home"

  get "about", to: "about#index", as: :about
  get "merch", to: "merch#index", as: :merch
  get "shows", to: "shows#index", as: :shows
  get "contact", to: "contact#index", as: :contact
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
#class StaticController < ApplicationController
  #def about
  #end

  def index
  end

  #def merch
  #end

  #def shows
  #end

  #def contact
  #end
end

app/controllers/merch_controller.rb
class MerchController < ApplicationController
    def index
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/about/index.html.erb
<h1>RedIsRecord</h1>
<p><%= image_tag "suit.jpeg", style: 'height:200%;width:auto;', alt: "Closeup of face wearing a suit and black bowtie" %></p>
<p>RedIsRecord is a multi-instrumentalist, music producer who started producing music using two tape decks. <br />
Realizing that the quality and workflow sucks, he pursued other options and has been doing so ever since.</p>
<hr />
<p><a href="https://soundcloud.com/redisrecord"><%= image_tag "soundcloud.jpeg", style: 'height:75%;width:auto;', alt: "Soundcloud Logo" %></a>
<p><a href="https://twitch.com/redisrecord"><%= image_tag "TwitchExtrudedWordmarkPurple.png", style: 'height:50%;width:auto;', alt: "Extruded Twitch Logo" %></a>

app/views/contact/index.html.erb
<h1>To Book RedIsRecord </h1>

<p>Text: <a class="nav-link" href="sms:+18505830842">850-583-0842</a></p>
<p>Call: <a class="nav-link" href="tel:+18505830842">850-583-0842</a></p>
<p>Email: <a class="nav-link" href="mailto: bkvagnini@gmail.com">bkvagnini@gmail.com</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedIsRecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <main>
    <%= yield %>
    </main>
    <footer>
    <hr>
     <%= image_tag("redisrecord_logo_tiny.png", style: 'height:50%;width:auto;', alt: "small RedIsRecord Logo")%> <%= render partial: "shared/navbar" %>

<p>&copy; 2023 <a href = "http://backbeat.agency">Backbeat Agency</a> </p>
    </footer>
  </body>
</html>

app/views/main/index.html.erb
<h1>RedIsRecord</h1>
<p><%= image_tag "redisrecord_logo.png", alt: "RedIsRecord Logo" %></p>
<%= image_tag "recordingreflections.jpg", alt: "Reflection of a Fostex Multitrack recorder", class: "hero" %>
<p>Playing LoFi jams and TripHop </p>

app/views/merch/index.html.erb
<h1>RedIsRecord Merch!</h1>
<p>Merch coming soon</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
<!--   <nav class="navbar navbar-expand-lg bg-body-tertiary"> -->
  <div class="container-fluid">
  <!--   <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Home</a>
          <!-- <a class="nav-link active" aria-current="page" href="/">Home</a> -->
        </li>
        <li class="nav-item">
          <%= link_to "About RedIsRecord", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Get Merch!", merch_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "See RedIsRecord perform!", shows_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact the team", contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shows/index.html.erb
<h1>RedIsRecord Performs Live!</h1>
<p>Shows coming soon</p>